- name: ID on hosts
  hosts: hosts
  become: True
  tasks: 
    - name: id on host
      ansible.builtin.command: id
      register: userid

    - name: show userid
      ansible.builtin.debug:
        msg: {{ userid }}
